### ISSUE TITLE
Member's View

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#168] opened 2019-12-10 01:41 UTC
I'd love to add member events to the calendar, but have the candidates not see it.

**Comment by dannychuy** [comment] 2019-12-10 01:42
This is so that we can add the Decal we hold, all the StudRel Events, and the meetings, HM, EM, etc.

**Comment by bri25yu** [comment] 2020-09-21 06:00
Duplicate of https://github.com/compserv/hknweb/issues/144

**Closed** 2020-09-21 06:01 UTC
Labels: low_priority
