### ISSUE TITLE
ModuleNotFoundError: No module named 'social_django'

### ISSUE THREAD

**Issue by cpkurotori** [compserv/hknweb#72] opened 2019-05-15 05:51 UTC
Was receiving the following error:

```
ModuleNotFoundError: No module named 'social_django'
Makefile:32: recipe for target 'migrate' failed
```

Perhaps it is the way that my computer was setup before, but upon searching I found that `pip install social-auth-app-django` should be run. I ran `pipenv run pip install social-auth-app-django` and this fixed the problem, but not sure if this is the correct way to go about things or not (maybe add to Pipfile).

#37 references getting rid of pipenv so this solution may not be relevant with changes to come, but wanted to mention it here so either setup can be fixed or setup documentation can mention the extra command.

**Comment by jameslzhu** [comment] 2019-05-17 06:35
The issue is, indeed, a missing dependency from the [Pipfile](https://github.com/compserv/hknweb/blob/master/Pipfile). #37 discusses issues with pipenv which are only tangentially related.

```toml
[packages]
...
social-auth-app-django = "~=3.1.0"
```

I think I opened up a pull request to merge this into the feature branch before it got merged into master, but it didn't happen. I've re-opened a pull request with the changes (which will need to be isolated).

**Closed** 2019-06-11 05:19 UTC
